### ISSUE TITLE
where is MoG model code? 

### ISSUE THREAD

**Issue by bhomass** [MelJan/PyDeep#10]
The paper mentions
GRBM-2-4, GRBM-2-4, and MoG-2-3 model, and report of results for MoG-9 in table 4,
as if there was a separate MoG model trained with eqn 24. 

is there implementation code for that? I don't find it anywhere. 

There is an overall question how the derivations on PoE and MoG come into the implementation at all. where are these concepts used? it seems we are just doing normal CD-k after all. Is the main lesson learned simply parameter initialization and gradient restriction?

**Comment by bhomass** [comment]
If MoG simply means take the trained W matrix and derive the anchor and first order components, then I understand what the paper is saying.

**Comment by MelJan** [comment]
Hi Bruce, 

the MoGs were trained using the scikit implementation for Mixture models, you can simply use this Implementation right away should be straight forward. I am curently on vacation but could provide code snips Approx. In a week from now.

Regarding your general question. 
The main contribution of the paper is that an GRBM is actually an MoG with described constraints. While these constraints make optimization way more diffcult they also lead to ICA like features, which MoGs do not. 

Second, from the theoretical learnings we derive the gradient restriction and show empirically that cd-1 with gradient restriction is actually enough and no need for advance sampling methods required, which makes training way more efficient.

Best Jan.
