### ISSUE TITLE
Online One-Shot Storage of Pattern Sequences

### ISSUE THREAD

**Issue by HugoChateauLaurent** [MelJan/PyDeep#5]
Hi!

Could you please make the code for https://arxiv.org/pdf/1905.12937.pdf available?

**Comment by MelJan** [comment]
Hi Hugo,

please have a look at PyDeep/examples/Example_Hebbian_descent.py , showing you how to implement a single layer e.g. CA3 for example. Is this what you are looking for? I can provide the full pipeline EC-DG-CA3-EC, but I need some free time to prepare it. Let me know if required. 

Best Jan

**Comment by HugoChateauLaurent** [comment]
I see, thank you!
