### ISSUE TITLE
Thesis link error

### ISSUE THREAD

**Issue by cossio** [MelJan/PyDeep#7]
The following link gives an error.

https://github.com/MelJan/PyDeep/blob/84c5d41942ab114bc8827ea2c10ea0a3d6dfdfd3/pydeep/rbm/trainer.py#L15

Can it be updated?

**Comment by MelJan** [comment]
Thanks for the hint, fixed it to 
https://www.ini.rub.de/PEOPLE/wiskott/Reprints/Melchior-2012-MasterThesis-RBMs.pdf
