### ISSUE TITLE
PyDeep is not installing

### ISSUE THREAD

**Issue by Harish11999** [MelJan/PyDeep#9]
![image](https://user-images.githubusercontent.com/108693125/231980874-4ad410b1-a4e5-4175-9da1-9afed13dcd2e.png)

There is an error while installing the package

**Comment by MelJan** [comment]
This pacakge is not listet in pypi, so by using pip install pydeep you are installing a different package that has the same name.
Please follow the Installation documentation i.e. Download the repository and pip install .
